server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # AUTH SERVICE
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # MAIN SERVICE
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/**

    compatibility-verifier:
      enabled: false

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
